# Generated by Django 3.2.13 on 2022-06-12 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_regist', models.DateField(auto_created=True, auto_now=True, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=11, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('image_profile', models.ImageField(blank=True, default='user.png', null=True, upload_to='users/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
