# Generated by Django 3.2.13 on 2022-06-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_slider_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='places-visits/')),
            ],
        ),
        migrations.CreateModel(
            name='Places_visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description_place', models.TextField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('img_cover', models.ImageField(blank=True, null=True, upload_to='places-visits/cover/')),
                ('operation', models.CharField(blank=True, help_text='Days of Operation', max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Closed'), ('R', 'Reform')], max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('K', 'Kids'), ('T', 'Teenager'), ('A', 'Adult')], max_length=30, null=True)),
                ('favorite', models.BooleanField(blank=True, default=False, null=True)),
                ('img', models.ManyToManyField(blank=True, null=True, to='plataform.image_slider_place')),
            ],
        ),
    ]
