# Generated by Django 4.0.5 on 2022-08-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places_visits',
            name='description_place',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='places_visits',
            name='operation',
            field=models.CharField(blank=True, help_text='Days of Operation', max_length=20, null=True),
        ),
    ]
