# Generated by Django 4.0.5 on 2022-08-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0004_alter_places_visits_description_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places_visits',
            name='description_place',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
